### ISSUE TITLE
Challenge 2 - error running chaos experiment

### ISSUE THREAD

**Issue by cdennig** [azuredevcollege/chaos-eng-workshop#18]
Hi @markuszm,

I'm getting an error when running the challenge-2 experiment: 

![image](https://user-images.githubusercontent.com/1263921/111756707-cec09200-889a-11eb-83e0-f4c8deb1f18e.png)

Checked the following:

- credentials are valid and AZURE_AUTH_LOCATION is initialized
- env variables are ok

Am I missing something?

**Comment by markuszm** [comment]
Could you try with chaostoolkit-azure version 0.9.0? They released a new version that should fix the issue. With that new version, we also don't need to pin to the old Azure library versions.
If this works, then we should update the challenge description.

**Comment by cdennig** [comment]
I already tried with version 0.9.0 and I just doubled-checked. Unfortunately, it does not solve the problem.

`Requirement already up-to-date: chaostoolkit-azure in /home/christian/.local/lib/python3.7/site-packages (0.9.0)`

**Comment by markuszm** [comment]
Just tried to reproduce, also get a different error now. Python 🙈  
Will try to find a fix.

**Comment by markuszm** [comment]
Can you try pinning your version to the old one and install the old Azure Python SDK dependencies :
```
pip install chaostoolkit-azure==0.8.3
pip install azure-mgmt-resourcegraph==2.0.0
pip install azure.mgmt.compute==7.0.0
```
this worked for me
I also changed the challenge description

**Comment by cdennig** [comment]
Works like a charm 👍 

![image](https://user-images.githubusercontent.com/1263921/111781202-7a2c0f80-88b8-11eb-8561-8fa8ae5304ef.png)

**Comment by cdennig** [comment]
Can you add the version pinning to the challenge?

**Comment by markuszm** [comment]
Done in https://github.com/azuredevcollege/chaos-eng-workshop/commit/8a32382f6373465ec90ccd9e42e26d5b0999a75f
